<%
require 'uri'
ENV['DATABASE_URL'] ||= "postgres://postgres@localhost/fraggers_development"
db_url = URI.parse(ENV['DATABASE_URL'])
%>

default: &default
  adapter:  postgresql
  username: <%= db_url.user %>
  password: <%= db_url.password %>
  host:     <%= db_url.host %>
  port:     <%= db_url.port %>
  database: <%= db_url.path.split('/')[1] %>
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fraggers_development

test:
  <<: *default
  database: fraggers_test

production:
  <<: *default
