default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

development:
  <<: *default
  database: fraggers_development

test:
  <<: *default
  database: fraggers_test

production:
  <<: *default
